MALE_FEMALE = (
    ('MALE', 'MALE'),
    ('FEMALE', 'FEMALE')
)

YES_NO = (
    ('YES', 'YES'),
    ('NO', 'NO')
)

YES_NO_UNSURE = (
    ('YES', 'YES'),
    ('NO', 'NO'),
    ('UNSURE', 'UNSURE')
)

YES_NO_DNTKNW = (
    ('YES', 'YES'),
    ('NO', 'NO'),
    ('Don\'t Know', 'Don\'t Know')
)

YES_NO_NEVER_HAD_SEX_DNTKNW = (
    ('YES', 'YES'),
    ('NO', 'NO'),
    ('NEVER HAD SEX', 'NEVER HAD SEX'),
    ('Don\'t Know', 'Don\'t Know')
)

EDUCATION = (
    ('NONE', 'NONE')
    ('NON-FORMAL', 'NON-FORMAL'),
    ('PRIMARY', 'PRIMARY'),
    ('JUNIOR SECONDARY', 'JUNIOR SECONDARY'),
    ('SENIOR SECONDARY', 'SENIOR SECONDARY'),
    ('HIGHER', 'HIGHER')
)

EMPLOYMENT_STATUS = (
    ('FULL-TIME', 'FULL-TIME EMPLOYED'),
    ('SELF', 'SELF EMPLOYED'),
    ('PART-TIME', 'PART-TIME EMPLOYED'),
    ('OWN', 'WORKING AT OWN LANDS/CATTLEPOST'),
    ('ACTIVELY SEEKING WORK', 'ACTIVELY SEEKING WORK'),
    ('TOO OLD TO WORK', 'TOO OLD TO WORK'),
    ('PENSIONER', 'PENSIONER'),
    ('STUDENT', 'STUDENT'),
    ('OTHER', 'OTHER')
)

MINE_OCCUPATION = (
    ('LOADER', 'LOADER'),
    ('BLASTER', 'BLASTER'),
    ('SHAFTMAN', 'SHAFTMAN'),
    ('FOREMAN', 'FOREMAN'),
    ('DRILLER', 'DRILLER'),
    ('OTHER', 'OTHER')
)

COMMODITY = (
    ('QUARRY', 'QUARRY'),
    ('COAL', 'COAL'),
    ('KIMBERLITE', 'KIMBERLITE'),
    ('COPPER/NICKLE', 'COPPER/NICKLE'),
    ('ASBESTOS', 'ASBESTOS'),
    ('OTHER', 'OTHER')
)

RELIGION = (
    ('CHRISTIANITY', 'CHRISTIANITY'),
    ('ISLAM', 'ISLAM'),
    ('BAHAI', 'BAHAI'),
    ('HINDUISM', 'HINDUISM'),
    ('BADIMO', 'BADIMO'),
    ('NO', 'NO RELIGION'),
    ('OTHER', 'OTHER')
)

TREATMENT_OPTIONS = (
    ('ANTIRETROVIRALS', 'ANTIRETROVIRALS'),
    ('TRADITIONAL HEALING', 'TRADITIONAL HEALING'),
    ('SPIRITUAL HEALING', 'SPIRITTUAL HEALING'),
    ('HERBAL', 'HERBAL'),
    ('NONE', 'NONE'),
    ('OTHER', 'OTHER,SPECIFY')
)

ARV_USES = (
    ('CURE AIDS', 'CURE AIDS'),
    ('CURE HIV', 'CURE HIV'),
    ('SUPPRESS HIV', 'SUPPRESS HIV'),
    ('DON’T KNOW', 'DON’T KNOW')
)

MARITAL_STATUS = (
    ('NEVER', 'NEVER MARRIED'),
    ('MARRIED', 'MARRIED'),
    ('LIVING TOGETHER', 'LIVING TOGETHER'),
    ('SEPARATED', 'SEPARATED'),
    ('DIVORCED', 'DIVORCED'),
    ('WIDOWED', 'WIDOWED')
)

SPOUSE_VISIT = (
    ('DAILY', 'DAILY'),
    ('WEEKLY', 'WEEKLY'),
    ('FORTNIGHTLY', 'FORTNIGHTLY'),
    ('MONTHLY', 'MONTHLY'),
    ('QUARTELY', 'QUARTELY'),
    ('YEARLY', 'YEARLY'),
    ('NEVER', 'NEVER')
)

TRANSMISSION_PREVENTION = (
    ('ANTIRETROVIRAL THERAPY', 'ANTIRETROVIRAL THERAPY (AZT, DRUGS BEFORE BIRTH)'),
    ('CAESAREAN SECTION', 'CAESAREAN SECTION'),
    ('DON’T KNOW', 'DON’T KNOW'),
    ('OTHER', 'OTHER,SPECIFY')
)

ARV_CONCERN = (
    ('LESS CONCERNED ', 'LESS CONCERNED '),
    ('MORE CONCERNED ', 'MORE CONCERNED '),
    ('DON’T KNOW', 'DON’T KNOW')
)

SEXUAL_BEHAVIOUR = (
    ('LESS CONDOM USE', 'LESS CONDOM USE'),
    ('MORE CONDOM USE', 'MORE CONDOM USE'),
    ('LESS SEXUAL PARTNERS', 'LESS SEXUAL PARTNERS'),
    ('MORE SEXUAL PARTNERS', 'MORE SEXUAL PARTNERS'),
    ('CONTINUE TO PRACTICE MULTIPLE AND CONCURRENT PARTNERSHIPS',
     'CONTINUE TO PRACTICE MULTIPLE AND CONCURRENT PARTNERSHIPS'),
    ('DISCONTINUE TO PRACTICE MULTIPLE AND CONCURRENT PARTNERSHIPS',
     'DISCONTINUE TO PRACTICE MULTIPLE AND CONCURRENT PARTNERSHIPS'),
    ('ABSTINENCE', 'ABSTINENCE'),
    ('DON’T KNOW', 'DON’T KNOW'),
    ('OTHER', 'OTHER, SPECIFY')
)

TB_INFECTION = (
    ('ANYBODY', 'ANYBODY'),
    ('ONLY POOR PEOPLE', 'ONLY POOR PEOPLE'),
    ('ONLY HOMELESS PEOPLE', 'ONLY HOMELESS PEOPLE'),
    ('ONLY ALCOHOLICS', 'ONLY ALCOHOLICS'),
    ('ONLY DRUG USERS', 'ONLY DRUG USERS'),
    ('ONLY PEOPLE LIVING WITH HIV AND AIDS',
     'ONLY PEOPLE LIVING WITH HIV AND AIDS'),
    ('ONLY PEOPLE WHO HAVE BEEN IN PRISON', 'ONLY PEOPLE WHO HAVE BEEN IN PRISON'),
    ('DON’T KNOW', 'DON’T KNOW'),
    ('OTHER', 'OTHER, SPECIFY')
)

TB_SPREAD = (
    ('SHARING A MEAL', 'SHARING A MEAL'),
    ('HUGGING', 'HUGGING'),
    ('SHARING CLOTHES', 'SHARING CLOTHES'),
    ('SEX WITH A WOMAN WHO MISCARRIED', 'SEX WITH A WOMAN WHO MISCARRIED'),
    ('SEX WITH A WIDOWER', 'SEX WITH A WIDOWER'),
    ('BORN IN A FAMILY WITH HIV', 'BORN IN A FAMILY WITH HIV'),
    ('HANDSHAKE', 'HANDSHAKE'),
    ('TOUCHING ITEMS IN PUBLIC PLACES ', 'TOUCHING ITEMS IN PUBLIC PLACES'
     '(Door knobs, etc.)'),
    ('DON’T KNOW', 'DON’T KNOW'),
    ('OTHER', 'OTHER, SPECIFY')
)

TB_CURE = (
    ('HERBAL REMEDIES', 'HERBAL REMEDIES'),
    ('HOME REST WITHOUT MEDICINE', 'HOME REST WITHOUT MEDICINE'),
    ('PRAYNG', 'PRAYING'),
    ('SPECIFIC DRUGS GIVEN BY HEALTH CENTER',
     'SPECIFIC DRUGS GIVEN BY HEALTH CENTER'),
    ('DOTS', 'DOTS')
)

SMC_SOURCE = (
    ('YOUTH PROGRAM', 'YOUTH PROGRAM'),
    ('TELEVISION/VIDEO', 'TELEVISION/VIDEO'),
    ('RADIO', 'RADIO'),
    ('NEWSPAPER', 'NEWSPAPER'),
    ('HOSPTAL/CLINIC/VCT', 'HOSPITAL/CLINIC/VCT'),
    ('POSTERS/BANNERS/BOOKLET', 'POSTERS/BANNERS/BOOKLET'),
    ('TRADITIONAL/SPIRITUAL HEALER', 'TRADITIONAL/ SPIRITUAL HEALER'),
    ('WORKSHOP/SEMINAR', 'WORKSHOP/SEMINAR'),
    ('INDIVIDUAL', 'INDIVIDUAL'),
    ('CHURCH', 'CHURCH'),
    ('KGOTLA', 'KGOTLA'),
    ('WORKPLACE PROGRAMME ',
     'WORKPLACE PROGRAMME ((PEER EDUCATOR, COUNSELLOR, CO-WORKER)'),
    ('PEER EDUCATOR', 'PEER EDUCATOR'),
    ('SCHOOL', 'SCHOOL'),
    ('OTHER', 'OTHER,SPECIFIY'))
