MALE_FEMALE = (
    ('MALE', 'MALE'),
    ('FEMALE', 'FEMALE')
)

YES_NO = (
    ('YES', 'YES'),
    ('NO', 'NO')
)

EDUCATION = (
    ('NONE', 'NONE')
    ('NON-FORMAL', 'NON-FORMAL'),
    ('PRIMARY', 'PRIMARY'),
    ('JUNIOR SECONDARY', 'JUNIOR SECONDARY'),
    ('SENIOR SECONDARY', 'SENIOR SECONDARY'),
    ('HIGHER', 'HIGHER')
)

EMPLOYMENT = (
    ('FULL-TIME', 'FULL-TIME EMPLOYED'),
    ('SELF', 'SELF EMPLOYED'),
    ('PART-TIME', 'PART-TIME EMPLOYED'),
    ('OWN', 'WORKING AT OWN LANDS/CATTLEPOST'),
    ('ACTIVELY SEEKING WORK', 'ACTIVELY SEEKING WORK'),
    ('TOO OLD TO WORK', 'TOO OLD TO WORK'),
    ('PENSIONER', 'PENSIONER')
    ('STUDENT', 'STUDENT')
)