MALE_FEMALE = (
    ('MALE', 'MALE'),
    ('FEMALE', 'FEMALE')
)

YES_NO = (
    ('YES', 'YES'),
    ('NO', 'NO')
)

YES_NO_DNTKNW = (
    ('YES', 'YES'),
    ('NO', 'NO'),
    ('Don\'t Know', 'Don\'t Know')
)

EDUCATION = (
    ('NONE', 'NONE')
    ('NON-FORMAL', 'NON-FORMAL'),
    ('PRIMARY', 'PRIMARY'),
    ('JUNIOR SECONDARY', 'JUNIOR SECONDARY'),
    ('SENIOR SECONDARY', 'SENIOR SECONDARY'),
    ('HIGHER', 'HIGHER')
)

EMPLOYMENT_STATUS = (
    ('FULL-TIME', 'FULL-TIME EMPLOYED'),
    ('SELF', 'SELF EMPLOYED'),
    ('PART-TIME', 'PART-TIME EMPLOYED'),
    ('OWN', 'WORKING AT OWN LANDS/CATTLEPOST'),
    ('ACTIVELY SEEKING WORK', 'ACTIVELY SEEKING WORK'),
    ('TOO OLD TO WORK', 'TOO OLD TO WORK'),
    ('PENSIONER', 'PENSIONER'),
    ('STUDENT', 'STUDENT'),
    ('OTHER', 'OTHER')
)

MINE_OCCUPATION = (
    ('LOADER', 'LOADER'),
    ('BLASTER', 'BLASTER'),
    ('SHAFTMAN', 'SHAFTMAN'),
    ('FOREMAN', 'FOREMAN'),
    ('DRILLER', 'DRILLER'),
    ('OTHER', 'OTHER')
)

COMMODITY = (
    ('QUARRY', 'QUARRY'),
    ('COAL', 'COAL'),
    ('KIMBERLITE', 'KIMBERLITE'),
    ('COPPER/NICKLE', 'COPPER/NICKLE'),
    ('ASBESTOS', 'ASBESTOS'),
    ('OTHER', 'OTHER')
)

RELIGION = (
    ('CHRISTIANITY', 'CHRISTIANITY'),
    ('ISLAM', 'ISLAM'),
    ('BAHAI', 'BAHAI'),
    ('HINDUISM', 'HINDUISM'),
    ('BADIMO', 'BADIMO'),
    ('NO', 'NO RELIGION'),
    ('OTHER', 'OTHER')
)
