# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 15:51
from __future__ import unicode_literals

from django.db import migrations, models
import edc_base.model_fields.custom_fields


class Migration(migrations.Migration):

    dependencies = [
        ('bais_subject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseholdQuestionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persons_list', models.CharField(max_length=50, verbose_name='Please give me names of all persons who slept with this household last night.')),
                ('person_household_head_rel', models.CharField(choices=[('HEAD', 'HEAD'), ('SPOUSE', 'SPOUSE'), ('SON/DAUGHTER', 'SON/DAUGHTER'), ('STEPCHILD', 'STEPCHILD'), ('GRANDCHILD', 'GRANDCHILD'), ('PARENT', 'PARENT'), ('GRANDPARENT', 'GRANDPARENT'), ('BROTHER/SISTER', 'BROTHER/SISTER'), ('NEPHEW/NIECE', 'NEPHEW/NEICE'), ('SON/DAUGHTER IN LAW', 'SON/DAUGHTER IN LAW'), ('PARENT IN LAW', 'PARENT IN LAW'), ('OTHER RELATIVE', 'OTHER RELATIVE'), ('NOT RELATED', 'NOT RELTED')], max_length=45, verbose_name="What is the person's relationship to head of this household?")),
                ('person_gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=45, verbose_name="What is the person's relationship to head of this household?")),
                ('person_age', models.CharField(help_text='RECORD EXACT AGE IN YEARS AND MONTHS FOR THOSE LESS THAN YEARS IN THE FORMAT( YY MM)', max_length=45, verbose_name='How old is the person in completed years?')),
                ('person_citizenship', models.CharField(choices=[('Botswana', 'Botswana'), ('Angola', 'Angola'), ('Lesotho', 'Lesotho'), ('Malawi', 'Malawi'), ('Mozambique', 'Mozambique'), ('Namibia', 'Namibia'), ('SouthAfrica', 'SouthAfrica'), ('Swaziland', 'Swaziland'), ('Zambia', 'Zambia'), ('Zimbabwe', 'Zimbabwe'), ('Tanzania', 'Tanzania'), ('India', 'India'), ('Mauritius', 'Mauritius'), ('UK', 'UK'), ('USA', 'USA'), ('Other', 'Other')], max_length=45, verbose_name="What is the country of person's citizenship?")),
                ('person_citizenship_other', edc_base.model_fields.custom_fields.OtherCharField(blank=True, editable=True, max_length=250, null=True, verbose_name='...if "Other", specify')),
                ('person_household_live', models.CharField(choices=[('Yes, spent the night', 'Yes, spent the night'), ('Yes, did not spend the night', 'Yes, did not spend the night'), ('No, visitor', 'No, visitor')], max_length=45, verbose_name='Does the person usually live in this household?')),
                ('person_marital_status', models.CharField(choices=[('NEVER', 'NEVER MARRIED'), ('MARRIED', 'MARRIED'), ('LIVING TOGETHER', 'LIVING TOGETHER'), ('SEPARATED', 'SEPARATED'), ('DIVORCED', 'DIVORCED'), ('WIDOWED', 'WIDOWED')], max_length=45, verbose_name="What is the person's current marital status?")),
                ('person_biological_mother_alive', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO'), ("Don't Know", "Don't Know")], max_length=45, verbose_name="Is the person's biological mother alive?")),
                ('person_biological_mother_household_live', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO'), ("Don't Know", "Don't Know")], max_length=45, verbose_name="Does the person's biological mother usually live in this household?")),
                ('person_biological_father_alive', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO'), ("Don't Know", "Don't Know")], max_length=45, verbose_name="Is the person's biological father alive?")),
                ('person_biological_father_household_live', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO'), ("Don't Know", "Don't Know")], max_length=45, verbose_name="Does the person's biological father usually live in this household?")),
                ('person_attended_school', models.CharField(choices=[('Yes, attending', 'Yes, attending'), ('Yes, left', 'Yes, left'), ('No', 'No')], max_length=45, verbose_name='Has the person ever attended school?')),
                ('person_currently_studying', models.CharField(choices=[('Primary', 'Primary'), ('Secondary', 'Secondary'), ('Tertiary', 'Tertiary'), ('None', 'None'), ("Don't know", "Don't know")], max_length=45, verbose_name='What level or grade is the person currently studying?')),
                ('person_highest_study_level', models.CharField(choices=[('Primary', 'Primary'), ('Secondary', 'Secondary'), ('Tertiary', 'Tertiary'), ('None', 'None'), ("Don't know", "Don't know")], max_length=45, verbose_name='What is the highest level that the person has completed?')),
                ('person_work_profit', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=45, verbose_name='In the past 7 days did the person work for payment, profit or home use for at least 1 hour?')),
                ('person_work_unpaid', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=45, verbose_name='Has the person worked unpaid at own lands/cattlepost, or unpaid in family business?')),
                ('person_work_unpaid_reason', models.CharField(choices=[('Actively seeking work', 'Actively seeking work'), ('Housework', 'Housework'), ('Student', 'Student'), ('Too old to work', 'Too old to work'), ('Too sick to work', 'Too sick to work'), ('Other', 'Other')], max_length=45, verbose_name='Since the person did not work for payment, profit or home use, what did he/she do?')),
                ('person_work_unpaid_reason_other', edc_base.model_fields.custom_fields.OtherCharField(blank=True, editable=True, max_length=250, null=True, verbose_name='...if "Other", specify')),
                ('person_main_work', models.CharField(choices=[('Employee - Paid cash  ', 'Employee - Paid cash  '), ('Employee - Paid in kind only  ', 'Employee - Paid in kind only  '), ('Self-employed(no employees)  ', 'Self-employed(no employees)  '), ('Self-employed(with employees)    ', 'Self-employed(with employees)    '), ('Member - Producer, Cooperatives ', 'Member - Producer, Cooperatives '), ('Unpaid helper in family business    ', 'Unpaid helper in family business    '), ('Working at own lands/cattlepost   ', 'Working at own lands/cattlepost   '), ('Apprentice    ', 'Apprentice    '), ('Volunteer', 'Volunteer')], max_length=45, verbose_name="What was the person's mainly working as during the past 7 days?")),
                ('person_work_type', models.CharField(help_text='To be precise, what were the main tasks and duties?', max_length=145, verbose_name='What type of work did the person do in the past 7 days?')),
                ('person_work_product', models.CharField(help_text='Probe as necessary.  Use two or more words to describe the Industry.', max_length=145, verbose_name="What was the main product, service or activity at the person's place of work?")),
            ],
        ),
        migrations.RemoveField(
            model_name='householdquestionnaireanswers',
            name='household_questionnaire_name',
        ),
        migrations.AlterField(
            model_name='section6',
            name='aids_hiv_times_tested',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=35, verbose_name='In the past 12 months how many times have you been tested for HIV and received your results?'),
        ),
        migrations.DeleteModel(
            name='HouseholdQuestionnaireAnswers',
        ),
        migrations.DeleteModel(
            name='HouseholdQuestionnaireName',
        ),
    ]
